// Command gengraphts generates the canonical TypeScript graph registry
// (server/ui/src/entities/graph/generated.ts) from the Go source of truth in
// sdk/ingest and sdk/common. Run it whenever the node/edge kind tables, edge
// endpoints, lens categories, or auth/truth enums change:
//
//	go run ./server/cmd/gengraphts
//
// The emitted file is DO-NOT-EDIT: the UI's dto.ts re-exports the unions from
// it, so Go and TypeScript can never drift.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/adithyan-ak/agenthound/sdk/common"
	"github.com/adithyan-ak/agenthound/sdk/ingest"
)

func main() {
	out := flag.String("out", defaultOutPath(), "output TypeScript file path")
	flag.Parse()

	data := render()
	if err := os.WriteFile(*out, data, 0o644); err != nil {
		log.Fatalf("write %s: %v", *out, err)
	}
	fmt.Printf("wrote %s (%d bytes)\n", *out, len(data))
}

// defaultOutPath resolves the generated.ts path relative to this source file,
// so `go run` works from any working directory.
func defaultOutPath() string {
	_, self, _, ok := runtime.Caller(0)
	if !ok {
		return "generated.ts"
	}
	root := filepath.Join(filepath.Dir(self), "..", "..", "..")
	return filepath.Join(root, "server", "ui", "src", "entities", "graph", "generated.ts")
}

func render() []byte {
	var b bytes.Buffer
	b.WriteString("// Code generated by server/cmd/gengraphts. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Canonical graph registry generated from the Go source of truth in\n")
	b.WriteString("// sdk/ingest (kinds.go, graphmeta.go) and sdk/common (states.go). Regenerate\n")
	b.WriteString("// with `go run ./server/cmd/gengraphts` after changing any of those tables.\n\n")

	// Node/edge kind unions.
	writeUnion(&b, "NodeKind", nodeKindNames())
	writeUnion(&b, "EdgeKind", edgeKindNames())

	// Lens + enum unions.
	writeUnion(&b, "LensCategory", lensCategoryNames())
	writeUnion(&b, "CollectionStatus", collectionStatusNames())
	writeUnion(&b, "StageState", stageStateNames())
	writeUnion(&b, "AuthScheme", authSchemeNames())
	writeUnion(&b, "AssessmentState", assessmentStateNames())

	// Node metadata.
	b.WriteString("export interface NodeKindMeta {\n")
	b.WriteString("  group: string;\n")
	b.WriteString("  collectorProduced: boolean;\n")
	b.WriteString("  umbrella: boolean;\n")
	b.WriteString("}\n\n")
	b.WriteString("export const NODE_KIND_META: Record<NodeKind, NodeKindMeta> = {\n")
	for _, m := range ingest.NodeKindMetadata {
		fmt.Fprintf(&b, "  %s: { group: %q, collectorProduced: %t, umbrella: %t },\n",
			tsKey(m.Kind), m.GroupLabel, m.CollectorProduced, m.Umbrella)
	}
	b.WriteString("};\n\n")

	// Edge metadata.
	b.WriteString("export interface EdgeKindMeta {\n")
	b.WriteString("  description: string;\n")
	b.WriteString("  lens: LensCategory;\n")
	b.WriteString("  composite: boolean;\n")
	b.WriteString("  directed: boolean;\n")
	b.WriteString("  sourceKinds: NodeKind[];\n")
	b.WriteString("  targetKinds: NodeKind[];\n")
	b.WriteString("}\n\n")
	b.WriteString("export const EDGE_KIND_META: Record<EdgeKind, EdgeKindMeta> = {\n")
	for _, m := range ingest.EdgeKindMetadata {
		ep := ingest.EdgeKindEndpoints[m.Kind]
		fmt.Fprintf(&b, "  %s: { description: %q, lens: %q, composite: %t, directed: %t, sourceKinds: %s, targetKinds: %s },\n",
			tsKey(m.Kind), m.Description, string(m.Lens), m.Composite, m.Directed,
			tsStringArray(ep.SourceKinds), tsStringArray(ep.TargetKinds))
	}
	b.WriteString("};\n\n")

	// Convenience arrays.
	writeStringArrayConst(&b, "NODE_KINDS", "NodeKind", nodeKindNames())
	writeStringArrayConst(&b, "EDGE_KINDS", "EdgeKind", edgeKindNames())

	return b.Bytes()
}

func writeUnion(b *bytes.Buffer, name string, values []string) {
	fmt.Fprintf(b, "export type %s =\n", name)
	for i, v := range values {
		sep := "|"
		if i == 0 {
			sep = "|"
		}
		term := ""
		if i == len(values)-1 {
			term = ";"
		}
		fmt.Fprintf(b, "  %s %q%s\n", sep, v, term)
	}
	b.WriteString("\n")
}

func writeStringArrayConst(b *bytes.Buffer, name, typ string, values []string) {
	fmt.Fprintf(b, "export const %s: readonly %s[] = [\n", name, typ)
	for _, v := range values {
		fmt.Fprintf(b, "  %q,\n", v)
	}
	b.WriteString("];\n\n")
}

// tsKey quotes an object key only when it is not a valid bare identifier.
// Graph kinds are all valid identifiers (letters/underscores), so this is a
// pass-through, but keep it defensive.
func tsKey(k string) string {
	valid := k != ""
	for i, r := range k {
		isLetter := r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')
		isDigit := r >= '0' && r <= '9'
		if !(isLetter || (isDigit && i > 0)) {
			valid = false
			break
		}
	}
	if valid {
		return k
	}
	return fmt.Sprintf("%q", k)
}

func tsStringArray(vals []string) string {
	if len(vals) == 0 {
		return "[]"
	}
	quoted := make([]string, len(vals))
	for i, v := range vals {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func nodeKindNames() []string {
	out := make([]string, len(ingest.NodeKindMetadata))
	for i, m := range ingest.NodeKindMetadata {
		out[i] = m.Kind
	}
	return out
}

func edgeKindNames() []string {
	out := make([]string, len(ingest.EdgeKindMetadata))
	for i, m := range ingest.EdgeKindMetadata {
		out[i] = m.Kind
	}
	return out
}

func lensCategoryNames() []string {
	out := make([]string, len(ingest.AllLensCategories))
	for i, v := range ingest.AllLensCategories {
		out[i] = string(v)
	}
	return out
}

func collectionStatusNames() []string {
	out := make([]string, len(ingest.AllCollectionStatuses))
	for i, v := range ingest.AllCollectionStatuses {
		out[i] = string(v)
	}
	return out
}

func stageStateNames() []string {
	out := make([]string, len(ingest.AllStageStates))
	for i, v := range ingest.AllStageStates {
		out[i] = string(v)
	}
	return out
}

func authSchemeNames() []string {
	out := make([]string, len(common.AllAuthSchemes))
	for i, v := range common.AllAuthSchemes {
		out[i] = string(v)
	}
	return out
}

func assessmentStateNames() []string {
	out := make([]string, len(common.AllAssessmentStates))
	for i, v := range common.AllAssessmentStates {
		out[i] = string(v)
	}
	return out
}
