export const OWASP_TITLES: Record<string, string> = {
  MCP01: "Excessive Agency",
  MCP02: "Insufficient Access Controls",
  MCP03: "Lack of Tool Guardrails",
  MCP04: "Tool Argument Injection",
  MCP05: "Prompt Injection via Tool Description",
  MCP06: "Lack of Monitoring/Logging",
  MCP07: "Insecure Plugin/Extension Trust",
  MCP08: "Lack of Rate Limiting",
  MCP09: "Insufficient Error Handling",
  MCP10: "Insecure Transport",
  ASI01: "Excessive Agency",
  ASI02: "Lack of Guardrails",
  ASI03: "Prompt Injection",
  ASI04: "Insecure Output Handling",
  ASI05: "Supply Chain Vulnerabilities",
  ASI06: "Insufficient Access Controls",
  ASI07: "Over-Reliance on AI Output",
  ASI08: "Data Leakage",
  ASI09: "Lack of Observability",
  ASI10: "Insufficient Monitoring",
};
