// Code generated by server/cmd/gengraphts. DO NOT EDIT.
//
// Canonical graph registry generated from the Go source of truth in
// sdk/ingest (kinds.go, graphmeta.go) and sdk/common (states.go). Regenerate
// with `go run ./server/cmd/gengraphts` after changing any of those tables.

export type NodeKind =
  | "MCPServer"
  | "MCPTool"
  | "MCPResource"
  | "MCPPrompt"
  | "A2AAgent"
  | "A2ASkill"
  | "AgentInstance"
  | "Identity"
  | "Credential"
  | "Host"
  | "ConfigFile"
  | "InstructionFile"
  | "OllamaInstance"
  | "VLLMInstance"
  | "QdrantInstance"
  | "MLflowServer"
  | "LiteLLMGateway"
  | "JupyterServer"
  | "LangServeApp"
  | "OpenWebUIInstance"
  | "AIService"
  | "AIModel"
  | "ExtractedTrainingSignal";

export type EdgeKind =
  | "TRUSTS_SERVER"
  | "PROVIDES_TOOL"
  | "PROVIDES_RESOURCE"
  | "PROVIDES_PROMPT"
  | "ADVERTISES_SKILL"
  | "DELEGATES_TO"
  | "AUTHENTICATES_WITH"
  | "USES_CREDENTIAL"
  | "RUNS_ON"
  | "CONFIGURED_IN"
  | "HAS_ENV_VAR"
  | "LOADS_INSTRUCTIONS"
  | "SAME_AUTH_DOMAIN"
  | "EXPOSES"
  | "EXPOSES_CREDENTIAL"
  | "PROVIDES_MODEL"
  | "EXTRACTED_FROM"
  | "INGESTS_UNTRUSTED"
  | "HAS_ACCESS_TO"
  | "CAN_EXECUTE"
  | "CAN_REACH"
  | "CAN_REACH_CROSS_PROTOCOL"
  | "CAN_REACH_CREDENTIAL_CHAIN"
  | "CAN_EXFILTRATE_VIA"
  | "SHADOWS"
  | "POISONED_DESCRIPTION"
  | "CAN_IMPERSONATE"
  | "POISONED_INSTRUCTIONS"
  | "CONFUSED_DEPUTY"
  | "TAINTS"
  | "IFC_VIOLATION"
  | "POISONS_CONTEXT";

export type LensCategory =
  | "topology"
  | "attack-surface"
  | "credentials"
  | "poisoning";

export type CollectionStatus =
  | "complete"
  | "partial"
  | "failed"
  | "unknown";

export type StageState =
  | "succeeded"
  | "partial"
  | "failed"
  | "skipped";

export type AuthScheme =
  | "none"
  | "basic"
  | "api_key"
  | "bearer"
  | "custom"
  | "oauth"
  | "oidc"
  | "signature"
  | "unknown";

export type AssessmentState =
  | "assessed"
  | "not_assessed"
  | "unknown";

export interface NodeKindMeta {
  group: string;
  collectorProduced: boolean;
  umbrella: boolean;
}

export const NODE_KIND_META: Record<NodeKind, NodeKindMeta> = {
  MCPServer: { group: "Servers", collectorProduced: true, umbrella: false },
  MCPTool: { group: "Tools & Skills", collectorProduced: true, umbrella: false },
  MCPResource: { group: "Resources", collectorProduced: true, umbrella: false },
  MCPPrompt: { group: "Tools & Skills", collectorProduced: true, umbrella: false },
  A2AAgent: { group: "Agents", collectorProduced: true, umbrella: false },
  A2ASkill: { group: "Tools & Skills", collectorProduced: true, umbrella: false },
  AgentInstance: { group: "Agents", collectorProduced: true, umbrella: false },
  Identity: { group: "Infra", collectorProduced: true, umbrella: false },
  Credential: { group: "Infra", collectorProduced: true, umbrella: false },
  Host: { group: "Infra", collectorProduced: true, umbrella: false },
  ConfigFile: { group: "Resources", collectorProduced: true, umbrella: false },
  InstructionFile: { group: "Resources", collectorProduced: true, umbrella: false },
  OllamaInstance: { group: "AI Services", collectorProduced: true, umbrella: false },
  VLLMInstance: { group: "AI Services", collectorProduced: true, umbrella: false },
  QdrantInstance: { group: "AI Services", collectorProduced: true, umbrella: false },
  MLflowServer: { group: "AI Services", collectorProduced: true, umbrella: false },
  LiteLLMGateway: { group: "AI Services", collectorProduced: true, umbrella: false },
  JupyterServer: { group: "AI Services", collectorProduced: true, umbrella: false },
  LangServeApp: { group: "AI Services", collectorProduced: true, umbrella: false },
  OpenWebUIInstance: { group: "AI Services", collectorProduced: true, umbrella: false },
  AIService: { group: "AI Services", collectorProduced: true, umbrella: true },
  AIModel: { group: "AI Models", collectorProduced: true, umbrella: false },
  ExtractedTrainingSignal: { group: "AI Models", collectorProduced: true, umbrella: false },
};

export interface EdgeKindMeta {
  description: string;
  lens: LensCategory;
  composite: boolean;
  directed: boolean;
  sourceKinds: NodeKind[];
  targetKinds: NodeKind[];
}

export const EDGE_KIND_META: Record<EdgeKind, EdgeKindMeta> = {
  TRUSTS_SERVER: { description: "Agent trusts MCP server", lens: "topology", composite: false, directed: true, sourceKinds: ["AgentInstance"], targetKinds: ["MCPServer"] },
  PROVIDES_TOOL: { description: "Server provides tool", lens: "topology", composite: false, directed: true, sourceKinds: ["MCPServer"], targetKinds: ["MCPTool"] },
  PROVIDES_RESOURCE: { description: "Server provides resource", lens: "topology", composite: false, directed: true, sourceKinds: ["MCPServer", "JupyterServer", "MLflowServer", "QdrantInstance"], targetKinds: ["MCPResource"] },
  PROVIDES_PROMPT: { description: "Server provides prompt template", lens: "topology", composite: false, directed: true, sourceKinds: ["MCPServer"], targetKinds: ["MCPPrompt"] },
  ADVERTISES_SKILL: { description: "A2A agent advertises skill", lens: "topology", composite: false, directed: true, sourceKinds: ["A2AAgent"], targetKinds: ["A2ASkill"] },
  DELEGATES_TO: { description: "Agent delegates to agent", lens: "topology", composite: false, directed: true, sourceKinds: ["A2AAgent"], targetKinds: ["A2AAgent"] },
  AUTHENTICATES_WITH: { description: "Authenticates with identity", lens: "credentials", composite: false, directed: true, sourceKinds: ["MCPServer", "A2AAgent"], targetKinds: ["Identity"] },
  USES_CREDENTIAL: { description: "Identity uses credential", lens: "credentials", composite: false, directed: true, sourceKinds: ["Identity"], targetKinds: ["Credential"] },
  RUNS_ON: { description: "Runs on host", lens: "topology", composite: false, directed: true, sourceKinds: ["MCPServer", "A2AAgent"], targetKinds: ["Host"] },
  CONFIGURED_IN: { description: "Configured in file", lens: "topology", composite: false, directed: true, sourceKinds: ["MCPServer"], targetKinds: ["ConfigFile"] },
  HAS_ENV_VAR: { description: "Has credential env var", lens: "credentials", composite: false, directed: true, sourceKinds: ["MCPServer"], targetKinds: ["Credential"] },
  LOADS_INSTRUCTIONS: { description: "Loads instruction file", lens: "topology", composite: false, directed: true, sourceKinds: ["AgentInstance"], targetKinds: ["InstructionFile"] },
  SAME_AUTH_DOMAIN: { description: "Shares auth domain", lens: "topology", composite: false, directed: false, sourceKinds: ["A2AAgent"], targetKinds: ["A2AAgent"] },
  EXPOSES: { description: "Exposes AI service", lens: "topology", composite: false, directed: true, sourceKinds: ["AIService"], targetKinds: ["AIService"] },
  EXPOSES_CREDENTIAL: { description: "Exposes credential material", lens: "credentials", composite: false, directed: true, sourceKinds: ["AIService"], targetKinds: ["Credential"] },
  PROVIDES_MODEL: { description: "Serves model artifact", lens: "topology", composite: false, directed: true, sourceKinds: ["OllamaInstance"], targetKinds: ["AIModel"] },
  EXTRACTED_FROM: { description: "Extracted from model", lens: "topology", composite: false, directed: true, sourceKinds: ["AIModel"], targetKinds: ["ExtractedTrainingSignal"] },
  INGESTS_UNTRUSTED: { description: "Ingests untrusted content", lens: "poisoning", composite: false, directed: true, sourceKinds: ["MCPTool"], targetKinds: ["MCPResource"] },
  HAS_ACCESS_TO: { description: "Tool can access resource", lens: "attack-surface", composite: true, directed: true, sourceKinds: ["MCPTool"], targetKinds: ["MCPResource"] },
  CAN_EXECUTE: { description: "Tool can execute on host", lens: "attack-surface", composite: true, directed: true, sourceKinds: ["MCPTool"], targetKinds: ["Host"] },
  CAN_REACH: { description: "Agent can reach resource", lens: "attack-surface", composite: true, directed: true, sourceKinds: ["AgentInstance", "A2AAgent"], targetKinds: ["MCPResource"] },
  CAN_REACH_CROSS_PROTOCOL: { description: "Agent can reach resource across protocols", lens: "attack-surface", composite: true, directed: true, sourceKinds: ["A2AAgent"], targetKinds: ["MCPResource"] },
  CAN_REACH_CREDENTIAL_CHAIN: { description: "Agent can reach upstream credential", lens: "credentials", composite: true, directed: true, sourceKinds: ["AgentInstance"], targetKinds: ["Credential"] },
  CAN_EXFILTRATE_VIA: { description: "Agent can exfiltrate via tool", lens: "attack-surface", composite: true, directed: true, sourceKinds: ["AgentInstance"], targetKinds: ["MCPTool"] },
  SHADOWS: { description: "Tool shadows another tool", lens: "poisoning", composite: true, directed: true, sourceKinds: ["MCPTool"], targetKinds: ["MCPTool"] },
  POISONED_DESCRIPTION: { description: "Poisoned tool description", lens: "poisoning", composite: true, directed: true, sourceKinds: ["MCPTool"], targetKinds: ["MCPTool"] },
  CAN_IMPERSONATE: { description: "Agent can impersonate agent", lens: "attack-surface", composite: true, directed: true, sourceKinds: ["A2AAgent"], targetKinds: ["A2AAgent"] },
  POISONED_INSTRUCTIONS: { description: "Poisoned instruction file", lens: "poisoning", composite: true, directed: true, sourceKinds: ["InstructionFile"], targetKinds: ["InstructionFile"] },
  CONFUSED_DEPUTY: { description: "Confused-deputy delegation", lens: "attack-surface", composite: true, directed: true, sourceKinds: ["A2AAgent"], targetKinds: ["A2AAgent"] },
  TAINTS: { description: "Taints downstream tool", lens: "poisoning", composite: true, directed: true, sourceKinds: ["MCPTool"], targetKinds: ["MCPTool"] },
  IFC_VIOLATION: { description: "Information-flow-control violation", lens: "poisoning", composite: true, directed: true, sourceKinds: ["MCPTool"], targetKinds: ["MCPTool"] },
  POISONS_CONTEXT: { description: "Poisons agent context", lens: "poisoning", composite: true, directed: true, sourceKinds: ["MCPTool"], targetKinds: ["MCPTool"] },
};

export const NODE_KINDS: readonly NodeKind[] = [
  "MCPServer",
  "MCPTool",
  "MCPResource",
  "MCPPrompt",
  "A2AAgent",
  "A2ASkill",
  "AgentInstance",
  "Identity",
  "Credential",
  "Host",
  "ConfigFile",
  "InstructionFile",
  "OllamaInstance",
  "VLLMInstance",
  "QdrantInstance",
  "MLflowServer",
  "LiteLLMGateway",
  "JupyterServer",
  "LangServeApp",
  "OpenWebUIInstance",
  "AIService",
  "AIModel",
  "ExtractedTrainingSignal",
];

export const EDGE_KINDS: readonly EdgeKind[] = [
  "TRUSTS_SERVER",
  "PROVIDES_TOOL",
  "PROVIDES_RESOURCE",
  "PROVIDES_PROMPT",
  "ADVERTISES_SKILL",
  "DELEGATES_TO",
  "AUTHENTICATES_WITH",
  "USES_CREDENTIAL",
  "RUNS_ON",
  "CONFIGURED_IN",
  "HAS_ENV_VAR",
  "LOADS_INSTRUCTIONS",
  "SAME_AUTH_DOMAIN",
  "EXPOSES",
  "EXPOSES_CREDENTIAL",
  "PROVIDES_MODEL",
  "EXTRACTED_FROM",
  "INGESTS_UNTRUSTED",
  "HAS_ACCESS_TO",
  "CAN_EXECUTE",
  "CAN_REACH",
  "CAN_REACH_CROSS_PROTOCOL",
  "CAN_REACH_CREDENTIAL_CHAIN",
  "CAN_EXFILTRATE_VIA",
  "SHADOWS",
  "POISONED_DESCRIPTION",
  "CAN_IMPERSONATE",
  "POISONED_INSTRUCTIONS",
  "CONFUSED_DEPUTY",
  "TAINTS",
  "IFC_VIOLATION",
  "POISONS_CONTEXT",
];

